---
apiVersion: v1
kind: Namespace
metadata:
  name: certificate-helper
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: certificates.certificate-helper.io
spec:
 group: certificate-helper.io
 names:
   plural: certificates
   singular: certificate
   kind: Certificate
   shortNames:
   - cert
   - crt
 scope: Cluster
 versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                service:
                  type: string
                alt_names:
                  type: array
                  items:
                    type: string
              required: ["namespace", "service"]
            status:
              type: object
              properties:
                certificate: 
                  type: string
                service:
                  type: string
                alt_names:
                  type: array
                  items: 
                    type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      message:
                        type: string
                      status:
                        type: string
                      last_transition_time:
                        type: string
                    x-kubernetes-preserve-unknown-fields: true
          required: ["spec"]
      subresources:
        status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: certificate-helper-service-account
  namespace: certificate-helper
secrets:
  - name: "certificate-helper.certificate-helper.svc"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role.certificate-helper.io
rules:
  - apiGroups:
    - certificates.k8s.io
    resources:
    - certificatesigningrequests
    verbs:
    - create
    - get
    - list
    - watch
    - delete
  - apiGroups:
    - certificates.k8s.io
    resources:
    - certificatesigningrequests/approval
    verbs:
    - update
    - get
    - delete
  - apiGroups:
    - certificates.k8s.io
    resources:
    - signers
    verbs:
    - approve
  - apiGroups:
      - certificate-helper.io
    resources:
      - certificates
      - certificates/status
    verbs: 
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
      - apps
      - rbac.authorization.k8s.io
      - certificates.k8s.io
    resources:
      - serviceaccounts
      - secrets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
    resourceNames:
      - kube-root-ca.crt
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: certificate-helper-cluster-rolebinding
  namespace: certificate-helper 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role.certificate-helper.io
subjects:
- namespace: certificate-helper 
  kind: ServiceAccount
  name: certificate-helper-service-account
---
apiVersion: webhook-helper.io/v1
kind: WebhookHelper
metadata:
  name: certificate-helper
spec: 
  namespace: certificate-helper
  listening_port: 8443
  webhook:
    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    metadata:
      name: certificate-helper
    webhooks:
      - name: certificate-helper
        rules:
          - operations: ["CREATE", "UPDATE", "DELETE"]
            apiGroups: ["certificate-helper.io"]
            apiVersions: ["v1"]
            resources: ["certificates"]
        failurePolicy: Fail
        admissionReviewVersions: ["v1", "v1beta1"]
        sideEffects: None
        timeoutSeconds: 5
  deployment:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: certificate-helper
      namespace: certificate-helper
      labels:
        app: certificate-helper
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: certificate-helper
      template:
        metadata:
          labels:
            app: certificate-helper
        spec:
          serviceAccountName: certificate-helper-service-account
          containers:
            - name: bootstrap
              image: rc1405/k8s-certificate-helper:latest
              args: ["run", "-p", "8443"]
              ports: 
                - containerPort: 8443